### ISSUE TITLE
Provide single Dockerfile with Mono, GrGen.NET, and BiGGer

### ISSUE THREAD

**Issue by abhishektiwari** [bigraph-toolkit-suite/bigraphs.grgen-bigraphs#2]
To streamline user workflow, provide single Dockerfile with Mono, GrGen.NET, and BiGGer installed ready to run.

[JOSS Review](https://github.com/openjournals/joss-reviews/issues/6491)

**Comment by PioBeat** [comment]
implemented in v1.2.0
